export const sampleProducts = [
    {
      name: "Nike Air Max",
      image: "https://i.ibb.co/HDGyB9Jf/image.jpg",
      description: "Comfortable running shoes for everyday wear",
      category: "Fashion",
      price: 120,
    },
    {
      name: "Atomic Habits",
      image: "https://i.ibb.co/p6cw4K1S/1619344052917-e-1759968000-v-beta-t-UWm-Ia70g-Rmn-EOHDupez-A6-DC-8e-Tb-I1-Gq-RK17rnp7-HQ.png",
      description: "A book about building better habits",
      category: "Books",
      price: 20,
    },
    {
      name: "Sony WH-1000XM5",
      image: "https://i.ibb.co/QvQtvqfy/Sony-WH-1000-XM4-scaled.jpg",
      description: "Noise-cancelling wireless headphones",
      category: "Electronics",
      price: 399,
    },
    {
      name: "Zara Summer Dress",
      image: "https://i.ibb.co/qLGWTG8c/08351047075-a1.jpg",
      description: "Lightweight dress for summer",
      category: "Fashion",
      price: 60,
    },
    {
      name: "Harry Potter and the Philosopher's Stone",
      image: "https://i.ibb.co/pBvdgxb0/81m9f-P-LIPL-SL1500.jpg",
      description: "Fantasy novel by J.K. Rowling",
      category: "Books",
      price: 25,
    },
    {
      name: "Samsung Galaxy S23",
      image: "https://i.ibb.co/NGSZFmt/shopping-q-tbn-ANd9-Gc-SQ1-Tw-DARVd-SGSIp-E8-LZc-Sq6-Zm-Kf9f5-KT3sy-Hal-Di-C8-Lv-CCXj-ZSv-VXpelv-K9h.webp",
      description: "Flagship Android phone with excellent display",
      category: "Electronics",
      price: 899,
    },
    {
      name: "Ray-Ban Sunglasses",
      image: "https://i.ibb.co/B5JsVmRq/download.jpg",
      description: "Classic aviator sunglasses",
      category: "Fashion",
      price: 150,
    },
    {
      name: "The Psychology of Money",
      image: "https://i.ibb.co/mVvTRfZ1/The-Psychologyof-Money-0.jpg",
      description: "Timeless lessons on wealth and behavior",
      category: "Books",
      price: 21,
    },
    {
      name: "iPhone 15",
      image: "https://i.ibb.co/zhJwJpcz/shopping-q-tbn-ANd9-Gc-Twmu8-Jvz-YSO-6-CKCs1-Queeb-Djtd-Pcmas-et-Vy16sidw-EY98-CBNr24l-M1zi-Vq-RXJma.webp",
      description: "Latest Apple smartphone with A17 chip",
      category: "Electronics",
      price: 999,
    },
    {
      name: "Puma Hoodie",
      image: "https://i.ibb.co/dw1Zqgrd/shopping-q-tbn-ANd9-Gc-Qr-Yid-Hh-UQSF-Fh-Qp85-YLf37-Fy5e-Eyq-PYPLC6-FQRS6-Yyz-WHg-ZHOu-Ccyjw-Gh02-Zp.webpe",
      description: "Comfortable cotton hoodie",
      category: "Fashion",
      price: 70,
    },
    {
      name: "Rich Dad Poor Dad",
      image: "https://i.ibb.co/B5k7B04z/rch-dwa-poor-dwa.png",
      description: "Personal finance classic",
      category: "Books",
      price: 22,
    },
    {
      name: "Converse Chuck Taylor",
      image: "https://i.ibb.co/Kc5PGyRs/images-q-tbn-ANd9-Gc-Sjp-X4-J05b-Lv-Akhlw-TINdz-QSy-PHQHURWC9b-Udje-Uf-Bie-Eb-NPY9-Ks-Johj-Y-s.jpg",
      description: "Classic high-top sneakers",
      category: "Fashion",
      price: 65,
    },
    {
      name: "Canon EOS R10",
      image: "https://i.ibb.co/6RLkDML2/nando-canon-eos-r10-00-jpg.webp",
      description: "Mirrorless camera for professionals",
      category: "Electronics",
      price: 1499,
    },
    {
      name: "Levi's 501 Jeans",
      image: "https://i.ibb.co/DgkGq19P/images-q-tbn-ANd9-Gc-Sdhc-4-KMg-Cregoo-Nm6hb-T560-TYB0-Wj-Di-U2kg-s.jpg",
      description: "Classic denim jeans",
      category: "Fashion",
      price: 90,
    },
    {
      name: "The Alchemist",
      image: "https://i.ibb.co/mr29CK0k/1679983034150.jpg",
      description: "Inspirational story by Paulo Coelho",
      category: "Books",
      price: 19,
    },
    {
      name: "Marshall KILBURN II",
      image: "https://i.ibb.co/5XgKLgr9/kilburn-ii-front-desktop-1.jpg",
      description: "Portable Bluetooth speaker",
      category: "Electronics",
      price: 199,
    },
    {
      name: "Gucci Belt",
      image: "https://i.ibb.co/ZRYS6mQR/shopping-q-tbn-ANd9-Gc-Snz0atfls-MI0g-RHg8-Ykz-S07u9-EEKw-G8g-BVXmo-NFfo-EG5-SV5d-Jl5xtl-Chft-DSgy-W.webp",
      description: "Luxury leather belt",
      category: "Fashion",
      price: 350,
    },
    {
      name: "To Kill a Mockingbird",
      image: "https://i.ibb.co/qM2jkBF2/images-q-tbn-ANd9-Gc-REx-Suh-Ybw-LM-1wi8-Fk-TTi-Rp-T3-V8p-Oc-BFC-Q-s.jpg",
      description: "Classic novel by Harper Lee",
      category: "Books",
      price: 17,
    },
    {
      name: "Logitech MX Master 3",
      image: "https://i.ibb.co/0Rf5GBTJ/images.jpg",
      description: "Ergonomic wireless mouse",
      category: "Electronics",
      price: 129,
    },
    {
      name: "Adidas Ultraboost",
      image: "https://i.ibb.co/Z6RFqHQW/images-q-tbn-ANd9-Gc-Sg-YYHw-Xu58pg4i7l-Rm-T4x-O9-Vo-Wu-Xw6x4jgtg-s.jpg",
      description: "High-performance sneakers with cushioning",
      category: "Fashion",
      price: 150,
    },
    {
      name: "1984",
      image: "https://i.ibb.co/GfmGzzdP/514-COylmq-RL-SL240-CATL-225-225-RO112-1-0-0-0-0-0-0-8.jpg",
      description: "Dystopian novel by George Orwell",
      category: "Books",
      price: 15,
    },
    {
      name: "Apple Watch Ultra",
      image: "https://i.ibb.co/Mk9G000q/MXTH3ref-VW-34-FR-watch-case-49-titanium-natural-ultra2-VW-34-FR-watch-face-49-ocean-ultra2-VW-34-FR.jpg",
      description: "Rugged smartwatch with GPS tracking",
      category: "Electronics",
      price: 799,
    },
    {
      name: "North Face Backpack",
      image: "https://i.ibb.co/s98ZSHMF/images-q-tbn-ANd9-Gc-Rfhmic-FVmh-ZJu-RDZo-IRFu-PJT4-BHatl-Pnp-O2-XWMGr4s-DJHi-W0y-V7-Jf-U9-YU-Ju-Xg.jpg",
      description: "Durable outdoor backpack",
      category: "Fashion",
      price: 110,
    },
    {
      name: "The Subtle Art of Not Giving a F*ck",
      image: "https://i.ibb.co/217Tvf4L/images-q-tbn-ANd9-Gc-RQZWB9ijzw-G8-Qk-Yv-QCp6z-TIsjlrj-UFyue-UWg-s.jpg",
      description: "Self-help bestseller by Mark Manson",
      category: "Books",
      price: 18,
    },
    {
      name: "MacBook Air M2",
      image: "https://i.ibb.co/Z6T1w2vp/71p-KJ-Mjd8-L-SL1500.jpg",
      description: "Lightweight Apple laptop with M2 chip",
      category: "Electronics",
      price: 1299,
    },
    {
      name: "H&M Jacket",
      image: "https://i.ibb.co/NddDNTBd/5587c19ed5b166729f1c4706a198fed0b0f1edda.jpg",
      description: "Stylish casual jacket",
      category: "Fashion",
      price: 80,
    },
    {
      name: "Sapiens: A Brief History of Humankind",
      image: "https://i.ibb.co/4nSDxwDH/6610000145997.jpg",
      description: "History of humankind by Yuval Noah Harari",
      category: "Books",
      price: 30,
    },
    {
      name: "Dell XPS 13",
      image: "https://i.ibb.co/tTdYjW6n/xps-9350-silver-thumb.jpg",
      description: "Premium ultrabook with thin bezels",
      category: "Electronics",
      price: 1199,
    },
    {
      name: "Zara Winter Coat",
      image: "https://i.ibb.co/x0CbhKt/03046273710-p.jpg",
      description: "Warm coat for cold winters",
      category: "Fashion",
      price: 180,
    },
    {
      name: "The Great Gatsby",
      image: "https://i.ibb.co/KcZB2MbD/gatsbycast.jpg",
      description: "Classic novel by F. Scott Fitzgerald",
      category: "Books",
      price: 16,
    },
  ]
  